'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace WS_BOOKING
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Service1Soap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Service1
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GETDATA_BY_BOOKIDOperationCompleted As System.Threading.SendOrPostCallback
        
        Private GETDATA_BY_BOOKID_ATTACHOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.FDA_FINANCE.My.MySettings.Default.FDA_FINANCE_WS_BOOKING_Service1
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GETDATA_BY_BOOKIDCompleted As GETDATA_BY_BOOKIDCompletedEventHandler
        
        '''<remarks/>
        Public Event GETDATA_BY_BOOKID_ATTACHCompleted As GETDATA_BY_BOOKID_ATTACHCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GETDATA_BY_BOOKID", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GETDATA_BY_BOOKID(ByVal BOOKID As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GETDATA_BY_BOOKID", New Object() {BOOKID})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GETDATA_BY_BOOKIDAsync(ByVal BOOKID As String)
            Me.GETDATA_BY_BOOKIDAsync(BOOKID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GETDATA_BY_BOOKIDAsync(ByVal BOOKID As String, ByVal userState As Object)
            If (Me.GETDATA_BY_BOOKIDOperationCompleted Is Nothing) Then
                Me.GETDATA_BY_BOOKIDOperationCompleted = AddressOf Me.OnGETDATA_BY_BOOKIDOperationCompleted
            End If
            Me.InvokeAsync("GETDATA_BY_BOOKID", New Object() {BOOKID}, Me.GETDATA_BY_BOOKIDOperationCompleted, userState)
        End Sub
        
        Private Sub OnGETDATA_BY_BOOKIDOperationCompleted(ByVal arg As Object)
            If (Not (Me.GETDATA_BY_BOOKIDCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GETDATA_BY_BOOKIDCompleted(Me, New GETDATA_BY_BOOKIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GETDATA_BY_BOOKID_ATTACH", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function GETDATA_BY_BOOKID_ATTACH(ByVal BOOKID As String) As System.Data.DataSet
            Dim results() As Object = Me.Invoke("GETDATA_BY_BOOKID_ATTACH", New Object() {BOOKID})
            Return CType(results(0),System.Data.DataSet)
        End Function
        
        '''<remarks/>
        Public Overloads Sub GETDATA_BY_BOOKID_ATTACHAsync(ByVal BOOKID As String)
            Me.GETDATA_BY_BOOKID_ATTACHAsync(BOOKID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GETDATA_BY_BOOKID_ATTACHAsync(ByVal BOOKID As String, ByVal userState As Object)
            If (Me.GETDATA_BY_BOOKID_ATTACHOperationCompleted Is Nothing) Then
                Me.GETDATA_BY_BOOKID_ATTACHOperationCompleted = AddressOf Me.OnGETDATA_BY_BOOKID_ATTACHOperationCompleted
            End If
            Me.InvokeAsync("GETDATA_BY_BOOKID_ATTACH", New Object() {BOOKID}, Me.GETDATA_BY_BOOKID_ATTACHOperationCompleted, userState)
        End Sub
        
        Private Sub OnGETDATA_BY_BOOKID_ATTACHOperationCompleted(ByVal arg As Object)
            If (Not (Me.GETDATA_BY_BOOKID_ATTACHCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GETDATA_BY_BOOKID_ATTACHCompleted(Me, New GETDATA_BY_BOOKID_ATTACHCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub GETDATA_BY_BOOKIDCompletedEventHandler(ByVal sender As Object, ByVal e As GETDATA_BY_BOOKIDCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GETDATA_BY_BOOKIDCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0")>  _
    Public Delegate Sub GETDATA_BY_BOOKID_ATTACHCompletedEventHandler(ByVal sender As Object, ByVal e As GETDATA_BY_BOOKID_ATTACHCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1055.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GETDATA_BY_BOOKID_ATTACHCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataSet
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataSet)
            End Get
        End Property
    End Class
End Namespace
