'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Frm_Budget_Overlap_Approve_OK

    '''<summary>
    '''btnRedirect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRedirect As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''dd_BudgetAdjust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dd_BudgetAdjust As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UC_Budget_Amount_Detail1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_Budget_Amount_Detail1 As Global.FDA_FINANCE.UC_Budget_Amount_Detail

    '''<summary>
    '''UC_Budget_Overlap_Approve_OK1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_Budget_Overlap_Approve_OK1 As Global.FDA_FINANCE.UC_Budget_Overlap_Approve_OK
End Class
