'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_Budgetplan_Detail

    '''<summary>
    '''lb_budget_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_budget_code As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_budget_code control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_budget_code As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lb_budget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_budget As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_BUDGET_DESCRIPTION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BUDGET_DESCRIPTION As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dd_type_6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dd_type_6 As Global.System.Web.UI.WebControls.DropDownList
End Class
