'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_Margin_Detail

    '''<summary>
    '''ddl_DO_TYPE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddl_DO_TYPE As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txt_DO_DATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_DO_DATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_DESCRIPITON control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_DESCRIPITON As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rnt_BUDGET_TYPE_AMOUNT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rnt_BUDGET_TYPE_AMOUNT As Global.Telerik.Web.UI.RadNumericTextBox
End Class
