'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_SendMoneyDepartment_Details

    '''<summary>
    '''txt_BANK_ACCOUNT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BANK_ACCOUNT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_DEPARTMENT_OR_BANK_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_DEPARTMENT_OR_BANK_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_BRANCH_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BRANCH_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_SHORT_DEPARTMENT_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_SHORT_DEPARTMENT_NAME As Global.System.Web.UI.WebControls.TextBox
End Class
