'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_Disburse_Debtor_Bill_Detail

    '''<summary>
    '''dd_KType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dd_KType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lb_K control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_K As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_GFMIS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_GFMIS As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_GFMIS_DATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_GFMIS_DATE As Global.System.Web.UI.WebControls.TextBox
End Class
