'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_Receive_List_Filter

    '''<summary>
    '''txt_DOC_NUMBER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_DOC_NUMBER As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''dl_User control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dl_User As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txt_BILL_NUMBER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_BILL_NUMBER As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rd_receive_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rd_receive_type As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''dd_equal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dd_equal As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txt_amount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_amount As Global.System.Web.UI.WebControls.TextBox
End Class
