'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Frm_Maintain_ReturnMoney_Debtor_OutsideBudget_Insert_Detail

    '''<summary>
    '''UC_Maintain_ReturnMoney_Detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_Maintain_ReturnMoney_Detail As Global.FDA_FINANCE.UC_Maintain_ReturnMoney_Detail

    '''<summary>
    '''btn_Save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_Save As Global.System.Web.UI.WebControls.Button
End Class
