'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_Maintain_ReturnMoney_OutsideBudget_Debtor_Information

    '''<summary>
    '''lbl_ContractNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ContractNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lb_level1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_level1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lb_level2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_level2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lb_level3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_level3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lb_level4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lb_level4 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Name As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_DebtorDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_DebtorDescription As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_Amount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_Amount As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_DeathlineDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_DeathlineDate As Global.System.Web.UI.WebControls.Label
End Class
