'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_Maintain_Deposit_Balance_Detail

    '''<summary>
    '''txt_date_save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_date_save As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_ACCOUNT_NUMBER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_ACCOUNT_NUMBER As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rnt_ACCOUNT_BALANCE_AMOUNT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rnt_ACCOUNT_BALANCE_AMOUNT As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''txt_CHECK_NUMBER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CHECK_NUMBER As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rnt_CHECK_AMOUNT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rnt_CHECK_AMOUNT As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''rnt_INTEREST_AMOUNT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rnt_INTEREST_AMOUNT As Global.Telerik.Web.UI.RadNumericTextBox
End Class
