'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_Maintain_Deposit_Money_Detail

    '''<summary>
    '''rdp_RECEIVE_DATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdp_RECEIVE_DATE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_RECEIPT_VOLUME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_RECEIPT_VOLUME As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_DEPOSIT_DESCRIPTION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_DEPOSIT_DESCRIPTION As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rbl_MONEY_TYPE_DESCRIPTION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbl_MONEY_TYPE_DESCRIPTION As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txt_DEPOSIT_AMOUNT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_DEPOSIT_AMOUNT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_DEPOSIT_DATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_DEPOSIT_DATE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Detail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Detail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_GF_NUMBER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_GF_NUMBER As Global.System.Web.UI.WebControls.TextBox
End Class
