'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_Maintain_ReceiveMoney_Information

    '''<summary>
    '''lbl_ShowMoneyReceiveAll control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ShowMoneyReceiveAll As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_ShowMoneyReceiveCash control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ShowMoneyReceiveCash As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_ShowMoneyReceiveCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ShowMoneyReceiveCheck As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_ShowMoneyReceiveTransfer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ShowMoneyReceiveTransfer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lbl_ShowMoneyReceiveCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_ShowMoneyReceiveCancel As Global.System.Web.UI.WebControls.Label
End Class
