'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_Maintain_ReceiveMoney_Detail_Receipt

    '''<summary>
    '''txt_RECEIPT_VOLUME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_RECEIPT_VOLUME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_RECEIPT_NUMBER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_RECEIPT_NUMBER As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_MONEY_RECEIVE_DATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_MONEY_RECEIVE_DATE As Global.System.Web.UI.WebControls.TextBox
End Class
