'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_Maintain_ReturnMoney_Debtor_Rebill_Receipt_Detail

    '''<summary>
    '''txt_bt_number control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_bt_number As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Changedate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Changedate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_CHANGE_DESCRIPTION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_CHANGE_DESCRIPTION As Global.System.Web.UI.WebControls.TextBox
End Class
