<?xml version="1.0" encoding="utf-8"?><Database Name="PROCURE" Class="LINQ_PROCUREMENTDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=THERDSAK-PC;Initial Catalog=PROCURE;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PROCUREConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="PROCUREMENT.PROCUREMENT_GUARANTEE_HEAD" Member="PROCUREMENT_GUARANTEE_HEADs">
    <Type Name="PROCUREMENT_GUARANTEE_HEAD">
      <Column Name="G_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PROJ_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOC_CODE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DETAIL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CREATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SUP_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="START_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="END_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="APPROVE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ACTION_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FINE_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FINE_RATE" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="FieldValue1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FieldValue2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FieldValue3" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FieldValue4" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FieldValue5" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FieldValue6" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FieldValue7" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FieldValue8" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FieldValue9" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FieldValue10" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FieldValue11" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FieldValue12" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="G_Type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="G_Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="G_Month" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="G_Day" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LOCATION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="INSTRUMENT_CHECK" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="INSTRUMENT_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="INSTRUMENT_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LEGEL_NO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LEGELSEND_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LEGEL_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="G_RETURNDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="G_RETURNNO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="G_RETURNMONEY" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="G_RETUENBIT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="G_RETURNREMARK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="G_RETURNAPPROVE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="G_RETURNNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="G_RETURNDATEDOC" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="G_FINE_TYPE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Proj_No" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="G_No" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Percents" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Result" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="PO_No" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>