<?xml version="1.0" encoding="utf-8"?><Database Name="FDA_MDC" Class="LINQ_FDA_MDCDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.111.28.134;Initial Catalog=FDA_MDC;Persist Security Info=True;User ID=fusion" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FDA_MDCConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.irgt" Member="irgts">
    <Type Name="irgt">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="process_id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lcn_prefixcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lcn_prefix" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lcnnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lcnlnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="pvncd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="rgttpcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="rgtno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rgtno_display" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rgtno_display_num" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rcvno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lcnsid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lcnscd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="laddrcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lctnmcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lctcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bsnid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="bsncd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rgtabbr" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="LOCATION_CHECK" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CONSIDER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="COMPLETE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="appvdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="appv_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="appv_position" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="fappvdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="expdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="fdano" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="cncstfcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cnccd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="cnccscd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="cncdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="thmblcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="amphrcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="chngwtcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="lstfcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lmdfdate" Type="System.DateTime" DbType="DateTime2" CanBeNull="true" />
      <Column Name="scpcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RCVNO_SHOW" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="RCVDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CITIZEN_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CITIZEN_ID_UPLOAD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CITIZEN_ID_AUTHORIZE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DOWN_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="XMLNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IMAGE_CODE" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="LCT_ADDR_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LCT_BSN_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LCN_SAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LCN_AMOUNT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="scope" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IMAGE_BSN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_CANCEL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_CONSIDER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PAYMENTCD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PAY_LAW_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PAY_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PAYAPPV_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LAW44_REF" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PAYMENT_REF" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STATUS_LAW_PAY" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="STATUS_PAY" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="STATUS_PAYAPPV" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="CHK_HIV" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="CHK_BLOOD" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="CHK_PROD" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="HOUSENO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LATITUDE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LONGTITUDE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IDENTIFY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ACADEMIC_STAFF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ADMIN_RCVNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ADMIN_RCVCITIZEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="human_age" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="human_nation" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="human_citizen_type" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="human_tel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="human_fax" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="human_email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STAFF_REPLACEMENTCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STAFF_REPLACEMENTNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TYPE_DB" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FDA_PAPER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ONESTOP_REQUEST" Member="ONESTOP_REQUESTs">
    <Type Name="ONESTOP_REQUEST">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PROCESS_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="WORK_PROCESS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lcnsid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TYPE_REQUESTS" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TYPE_REQUESTS_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REQUESTS_DATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="ALLOW_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN_ID_AUTHORIZE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CITIZEN_ID_UPLOAD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="REQUESTS_AUTHORITIES" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="AUTHORITIES_APPV" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN_ID_REQUESTS" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RESPONSIBLE_AUTHORITIES" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CONREQ_CREATION_DATE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CONREQ_LAST_UPDATE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CONREQ_PDF_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CONREQ_NUMBER_DAY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CONREQ_APPOINTMENT_DATE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RCVNO_DISPLAY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RCVNO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="REQUESTS_DATE_DISPLAY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="WORK_GROUP_NAME" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="WORK_GROUP_ID" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TXT_LCNNO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SUB_TYPE_REQUESTS" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ACTIVE" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="MDC_NAME_THAI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MDC_NAME_ENG" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS_PAY" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MDC_EXPORT" Member="MDC_EXPORTs">
    <Type Name="MDC_EXPORT">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="process_id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="pvncd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lcnsid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="scope" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="standard_detail_bsn" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="standard_detail_edit1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="standard_detail_edit2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="standard_detail_edit3" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="standard_detail_edit4" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="standard_detail_edit5" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="standard_detail_staff" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EDIT_MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EDIT_CITIZEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rcvno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RCVNO_DISPLAY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rcvdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="rgtno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rgtno_display" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rgtno_display_num" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="explain_date" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="appvdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="appv_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="appv_position" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="expdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="APPOINTMENT_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CONSIDER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="COMPLETE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lmdfdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LOCATION_ADDRESS_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOWN_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CITIZEN_ID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN_ID_UPLOAD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="XMLNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thanameplace" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="engnameplace" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thaaddr" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="engaddr" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="tharoom" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="thamu" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="thafloor" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="thasoi" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="thabuilding" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="engsoi" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="tharoad" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="engroad" Type="System.String" DbType="VarChar(80)" CanBeNull="true" />
      <Column Name="zipcode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tel" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="VarChar(60)" CanBeNull="true" />
      <Column Name="EMAIL" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="HOUSENO" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Branch" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="thmblcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="amphrcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="chngwtcd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="thathmblnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thaamphrnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thachngwtnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="engthmblnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="engamphrnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="engchngwtnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IDENTIFY" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="REMARK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_EXPLAIN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_CONSIDER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_CANCEL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FORWARD_EXPERT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="COMMENT_BSN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="write_at" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="write_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STATUS_ATTACH" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STATUS_ATTACH_STAFF" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="PAY_LAW_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PAYMENT_REF" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PAY_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PAYAPPV_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LAW44_REF" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STATUS_LAW_PAY" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="STATUS_PAY" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="STATUS_PAYAPPV" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="ACADEMIC_STAFF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ADMIN_RCVNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ADMIN_RCVCITIZEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STAFF_REPLACEMENTCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STAFF_REPLACEMENTNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FDA_PAPER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MDC_MC" Member="MDC_MCs">
    <Type Name="MDC_MC">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="process_id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="pvncd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lcnsid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rgttype" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="rgttpcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rgtno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rgtno_display" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rgtno_display_num" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MFT_NM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MFT_ADDR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MFT_COUNTRY" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="MFT_PLACE_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MFT_PLACE_ADDR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MFT_PLACE_COUNTRY" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="CERTIFICATE_SALE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CERTIFICATE_COUNTRY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Owntrgncd" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CFSNo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="gmpno" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="pdtno" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="CFSIssueDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CFSExpDate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CntAbbr" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Docno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FlwCntCd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FlwCntNM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="AppvCd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Appvlist" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lstfcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lmdfdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOWN_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CITIZEN_ID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN_ID_UPLOAD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="XMLNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="XML_DATABANK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="rcvno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RCVNO_DISPLAY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rcvdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="appvdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="appv_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="appv_position" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="expdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CONSIDER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="COMPLETE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CONSIDER_APPV" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDENTIFY" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="REMARK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_EXPLAIN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_CANCEL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_CONSIDER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FORWARD_EXPERT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PAY_LAW_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PAY_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PAYAPPV_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LAW44_REF" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PAYMENT_REF" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STATUS_LAW_PAY" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="STATUS_PAY" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="STATUS_PAYAPPV" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="write_at" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="write_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ACADEMIC_STAFF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ADMIN_RCVNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ADMIN_RCVCITIZEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STAFF_REPLACEMENTCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STAFF_REPLACEMENTNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FDA_PAPER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MDC_MN" Member="MDC_MNs">
    <Type Name="MDC_MN">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="process_id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="pvncd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lcnsid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rgttype" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="rgttpcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rgtno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rgtno_display" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rgtno_display_num" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="thamdnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="engmdnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="scope" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SCOPE_DETAIL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="international_code" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="manufacture_addr" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="responsible_addr" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="executive_summary" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NAMETH_EDIT1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NAMETH_EDIT2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="standard_detail_edit1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="standard_detail_edit2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="standard_detail_edit3" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="standard_detail_edit4" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="standard_detail_staff" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MANUFACTURE_ADDR_EDIT1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MANUFACTURE_ADDR_EDIT2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MANUFACTURE_ADDR_EDIT3" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MANUFACTURE_ADDR_EDIT4" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EDIT_MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EDIT_CITIZEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lstfcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lmdfdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOWN_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CITIZEN_ID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN_ID_UPLOAD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="XMLNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="rcvno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RCVNO_DISPLAY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rcvdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="appvdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="appv_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="appv_position" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="expdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CONSIDER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="COMPLETE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CONSIDER_APPV" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDENTIFY" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="REMARK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_EXPLAIN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_CANCEL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_CONSIDER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FORWARD_EXPERT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PAY_LAW_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PAY_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PAYAPPV_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LAW44_REF" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PAYMENT_REF" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STATUS_LAW_PAY" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="STATUS_PAY" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="STATUS_PAYAPPV" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="write_at" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="write_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ACADEMIC_STAFF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ADMIN_RCVNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ADMIN_RCVCITIZEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STAFF_REPLACEMENTCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STAFF_REPLACEMENTNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FDA_PAPER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MDC_MR" Member="MDC_MRs">
    <Type Name="MDC_MR">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="process_id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="pvncd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lcnsid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rgttype" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="rgttpcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rgtno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rgtno_display" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rgtno_display_num" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="thamdnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="engmdnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="scope" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SCOPE_DETAIL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="international_code" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="manufacture_addr" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="responsible_addr" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="executive_summary" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NAMETH_EDIT1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NAMETH_EDIT2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="standard_detail_edit1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="standard_detail_edit2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="standard_detail_edit3" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="standard_detail_edit4" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="standard_detail_edit5" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="standard_detail_staff" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MANUFACTURE_ADDR_EDIT1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MANUFACTURE_ADDR_EDIT2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MANUFACTURE_ADDR_EDIT3" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EDIT_MODIFYDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EDIT_CITIZEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lstfcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lmdfdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOWN_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CITIZEN_ID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN_ID_UPLOAD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="XMLNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="rcvno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RCVNO_DISPLAY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rcvdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="appvdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="appv_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="appv_position" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="expdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CONSIDER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="COMPLETE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CONSIDER_APPV" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDENTIFY" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="REMARK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_EXPLAIN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_CANCEL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_CONSIDER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FORWARD_EXPERT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PAY_LAW_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PAY_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PAYAPPV_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LAW44_REF" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PAYMENT_REF" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STATUS_LAW_PAY" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="STATUS_PAY" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="STATUS_PAYAPPV" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="write_at" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="write_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ACADEMIC_STAFF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ADMIN_RCVNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ADMIN_RCVCITIZEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STAFF_REPLACEMENTCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STAFF_REPLACEMENTNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FDA_PAPER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MDC_DIAGNOSED" Member="MDC_DIAGNOSEDs">
    <Type Name="MDC_DIAGNOSED">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="process_id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="pvncd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lcnsid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rgttype" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="rgttpcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rgtno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rgtno_display" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rgtno_display_num" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PRODUCT_HEAD_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PRODUCT_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VERSION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MANUFACTURER_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MANUFACTURER_ADDR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="COUNTRY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="INTENDED_USE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MDC_SCOPE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DIALOGUE1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DIALOGUE2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DIALOGUE3" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lstfcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lmdfdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOWN_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CITIZEN_ID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN_ID_UPLOAD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="XMLNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="rcvno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RCVNO_DISPLAY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rcvdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="appvdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="appv_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="appv_position" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="expdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CONSIDER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="COMPLETE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CONSIDER_APPV" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDENTIFY" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="REMARK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_EXPLAIN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_CANCEL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_CONSIDER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FORWARD_EXPERT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PAY_LAW_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PAY_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PAYAPPV_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LAW44_REF" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PAYMENT_REF" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STATUS_LAW_PAY" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="STATUS_PAY" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="STATUS_PAYAPPV" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="write_at" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="write_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ACADEMIC_STAFF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ADMIN_RCVNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ADMIN_RCVCITIZEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STAFF_REPLACEMENTCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STAFF_REPLACEMENTNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FDA_PAPER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MDC_EDIT" Member="MDC_EDITs">
    <Type Name="MDC_EDIT">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="process_id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="pvncd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lcnsid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LCT_FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="YEAR" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ROUND" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rgttype" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="rgttpcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rgtno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rgtno_display" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rgtno_display_num" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="EDIT_REMARK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="EDITNO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EDIT_APPV_MC" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EDITNO_DISPLAY" Type="System.String" DbType="NChar(50)" CanBeNull="true" />
      <Column Name="lmdfdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOWN_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CITIZEN_ID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN_ID_UPLOAD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="XMLNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="XML_DATABANK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FORWARD_EXPERT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rcvno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RCVNO_DISPLAY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rcvdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="appvdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="appv_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="appv_position" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="expdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CONSIDER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="COMPLETE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CONSIDER_APPV" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDENTIFY" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="REMARK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_EXPLAIN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_CANCEL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_CONSIDER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PAY_LAW_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PAY_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PAYAPPV_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LAW44_REF" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PAYMENT_REF" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STATUS_LAW_PAY" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="STATUS_PAY" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="STATUS_PAYAPPV" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="write_at" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="write_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ACADEMIC_STAFF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ADMIN_RCVNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ADMIN_RCVCITIZEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STAFF_REPLACEMENTCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STAFF_REPLACEMENTNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FDA_PAPER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="TYPE_EDIT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TYPE_MOVE" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TYPE_LCT" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MDC_CER" Member="MDC_CERs">
    <Type Name="MDC_CER">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="process_id" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="pvncd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lcnsid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rgttype" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="rgttpcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lctno" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lcnno" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lcnno_display" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lcnno_display_num" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="cer_no" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cer_type" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="for_no" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="for_type" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="country" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="country_no" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="subtype_no" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="export_amount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="producer_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="producer_lct" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="contact_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="contact_phone" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="contact_email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="petitioner_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="company_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="cer_path" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lstfcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lmdfdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOWN_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CITIZEN_ID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN_ID_UPLOAD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="XMLNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="condate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="rcvno" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RCVNO_DISPLAY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="rcvdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="fappvdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="appvdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="appv_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="appv_position" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="expdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CONSIDER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="COMPLETE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CONSIDER_APPV" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDENTIFY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_EXPLAIN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_CANCEL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_CONSIDER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FORWARD_EXPERT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PAY_LAW_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PAY_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PAYAPPV_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LAW44_REF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PAYMENT_REF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STATUS_LAW_PAY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STATUS_PAY" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STATUS_PAYAPPV" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="write_at" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="write_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ACADEMIC_STAFF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ACADEMIC_POSITION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ACADEMIC_POSITION_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ADMIN_RCVNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ADMIN_RCVCITIZEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STAFF_REPLACEMENTCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STAFF_REPLACEMENTNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FDA_PAPER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TYPE_DB" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MDC_SUBSTITUTE" Member="MDC_SUBSTITUTEs">
    <Type Name="MDC_SUBSTITUTE">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="process_id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="pvncd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lcnsid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LCT_FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rgttype" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="TYPE" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="rgttpcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="rgtno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rgtno_display" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rgtno_display_num" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SUBSTITUTE_TYPE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SUBSTITUTE_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lstfcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lmdfdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DOWN_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CITIZEN_ID" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN_ID_UPLOAD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="XMLNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="rcvno" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RCVNO_DISPLAY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rcvdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="appvdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="appv_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="appv_position" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="expdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CONSIDER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="COMPLETE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CONSIDER_APPV" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDENTIFY" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="REMARK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_EXPLAIN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CASE_CANCEL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_CANCEL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_CONSIDER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PAY_LAW_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PAY_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PAYAPPV_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LAW44_REF" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PAYMENT_REF" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STATUS_LAW_PAY" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="STATUS_PAY" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="STATUS_PAYAPPV" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="write_at" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="write_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ACADEMIC_STAFF" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ADMIN_RCVNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ADMIN_RCVCITIZEN" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STAFF_REPLACEMENTCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STAFF_REPLACEMENTNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FDA_PAPER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.IMPORT_OT" Member="IMPORT_OTs">
    <Type Name="IMPORT_OT">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="lcnsid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="process_id" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="COMPANY_IDENTIFY" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="COMPANY_NM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="RCVNO_TYPE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rcvno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RCVNO_DISPLAY" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="RCVDATE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="lcnno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LCNNO_DISPLAY" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="appvdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="expdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FK_IDA" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TR_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TYPE_OT" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="LCNNO_TYPE_CD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LCNNO_TYPE_NM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BSN_TYPE" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="BN" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="BSN_BRANCH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_FLOOR" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BSN_POSITION" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TYPE_DEPARTMENT" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="TYPE_REMARK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="BSN_IDENTIFY" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="BSN_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LCN_TYPE" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="LCNNO_STATION" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LCN_APPVDATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="thanm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thaaddr" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="room" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="mu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="floor" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thasoi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="building" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tharoad" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thmblcd" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="amphrcd" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="chngwtcd" Type="System.String" DbType="NVarChar(3)" CanBeNull="true" />
      <Column Name="thathmblnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thaamphrnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thachngwtnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="engthmblnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="engamphrnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="engchngwtnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="zipcode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="tel" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="houseno" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="pvncd" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PURPOST_MANUFACTURE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PURPOST_IMPORT" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="PURPOST_SALE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PURPOST_REMARK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PURPOST_NAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PURPOST_TYPE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PURPOST_KIND" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PURPOST_AMOUNT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PURPOST_FOR" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PURPOST_CHK_FOR" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="DETAIL_CHK" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="INTENDED_USE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STANDARD" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN_ID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CITIZEN_ID_UPLOAD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CITIZEN_ID_AUTHORIZE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DOWN_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="lmdfdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="XMLNAME" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IDENTIFY" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="write_at" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="write_date" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LAW44_REF" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PAYMENT_REF" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="STATUS_LAW_PAY" Type="System.String" DbType="NVarChar(2)" CanBeNull="true" />
      <Column Name="STATUS_PAY" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="STATUS_PAYAPPV" Type="System.String" DbType="NVarChar(1)" CanBeNull="true" />
      <Column Name="REMARK" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_CONSIDER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="REMARK_CANCEL" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CONSIDER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="newcode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="STAFF_REPLACEMENTCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STAFF_REPLACEMENTNM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="FDA_PAPER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="thamdcnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="engmdcnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="unit" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="bookno" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Column Name="PAY_DAY" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PAYAPPV_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
</Database>