'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://ephemeris.fda.moph.go.th/DocWebService/DOCService.svc")>  _
        Public ReadOnly Property FDA_FINANCE_WS_PERSONAL_DEPARTMENT_DOCService() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_PERSONAL_DEPARTMENT_DOCService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://ephemeris.fda.moph.go.th/IDEM/Service/IDEMService.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_IDEM_IDEMService() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_IDEM_IDEMService"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.161/ws_update_stat/WS_UPDATE.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_UPDATE_PAY_WS_UPDATE_STATUS_PAY() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_UPDATE_PAY_WS_UPDATE_STATUS_PAY"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.125/WS_CMT_PAY/WS_CMT_PAY.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_CMT_PAYS_WS_CMT_PAY() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_CMT_PAYS_WS_CMT_PAY"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.108/ws_edoc/Service1.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_BOOKING_Service1() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_BOOKING_Service1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.137/TEST_FLATEN/WS_FLATTEN.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_FLATTEN_WS_FLATTEN() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_FLATTEN_WS_FLATTEN"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.125/cmt_cer_location/WS_Update_Payment_CER_LOCATION.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_Update_Payment_CER_LOCATION_WS_Update_Payment_CER_LOCATION() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_Update_Payment_CER_LOCATION_WS_Update_Payment_CER_LOCATION"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.108/WS_CENTER/WS_CENTER.ASMX")>  _
        Public ReadOnly Property FDA_FINANCE_WS_CENTER_WS_CENTER() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_CENTER_WS_CENTER"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.108/WS_Taxno_TaxnoAuthorize/WS_Taxno_TaxnoAuthorize.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_Taxno_TaxnoAuthorize_WebService1() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_Taxno_TaxnoAuthorize_WebService1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.103/WS_STATUS_PAY/Service1.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_STATUS_PAY_Service1() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_STATUS_PAY_Service1"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.105/WS_INSERT_XML/WS_INSERT_XML/NCT_INSERT_XML.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_NCT_INSERT_XML_NCT_INSERT_XML() As String
            Get
                Return CType(Me("FDA_FINANCE_NCT_INSERT_XML_NCT_INSERT_XML"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.105/WS_INSERT/WS_INSERT/WS_NCT_INSERT.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_NCT_INSERT_WS_NCT_INSERT() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_NCT_INSERT_WS_NCT_INSERT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.133/FDA_MDC_DEMO/WEBSERVICE/UPDATE_RCVNO.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_UPDATE_RCVNO_UPDATE_RCVNO() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_UPDATE_RCVNO_UPDATE_RCVNO"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.133/FDA_MDC/WEBSERVICE/SV_UPDATE_DATE.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_UPDATE_DATE_MDC_SV_UPDATE_DATE() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_UPDATE_DATE_MDC_SV_UPDATE_DATE"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.103/WS_FDA_DOC/WS_FDA_BG.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_FDA_BG_DOC_WS_FDA_BG() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_FDA_BG_DOC_WS_FDA_BG"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.108/Mail/FDA_MAIL.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_FDA_MAIL_FDA_MAIL() As String
            Get
                Return CType(Me("FDA_FINANCE_FDA_MAIL_FDA_MAIL"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.129/FDA_DRUG/WS_GEN_DH_NO.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_GEN_DH_NUMBER_WS_GEN_DH_NO() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_GEN_DH_NUMBER_WS_GEN_DH_NO"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://164.115.28.102/CERTIFICATE/WS_Update_Payment_Cer.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_CER_CMT_WS_Update_Payment_Cer() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_CER_CMT_WS_Update_Payment_Cer"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.131/FDA_FOOD/WS_FOOD_JOB.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_FOOD_WS_FOOD_JOB() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_FOOD_WS_FOOD_JOB"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.103/fda_budget/WS_OLD_DT.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_OLD_DTS_WS_OLD_DT() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_OLD_DTS_WS_OLD_DT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.105/WS_ERROR_CENTER/WEB_SERVICE/WS_ERROR_CENTER.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_ERROR_CENTERS_WS_ERROR_CENTER() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_ERROR_CENTERS_WS_ERROR_CENTER"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://pengera.fda.moph.go.th/WS_SPECIAL_PAYMENT/WS_SPM/WS_UPDATE_PAYMENT.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_UPDATE_PAYMENT_SV_UPDATE_PAYMENT() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_UPDATE_PAYMENT_SV_UPDATE_PAYMENT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.108/WS_FDA_QR/WS_QR.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_QR_WS_QR() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_QR_WS_QR"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.161/WS_RUN_PDF_RECEIPT/WS_RUN_PDF_RECEIPT.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_RUN_PDF_RECEIPT_WS_RUN_PDF_RECEIPT() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_RUN_PDF_RECEIPT_WS_RUN_PDF_RECEIPT"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://pertento.fda.moph.go.th/Certificate_narcotic/WS_UPDATE_PAYMENT_CER.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_UPDATE_PAYMENT_CERS_WS_UPDATE_PAYMENT_CER() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_UPDATE_PAYMENT_CERS_WS_UPDATE_PAYMENT_CER"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://172.17.0.100/FDA_INSERT_XML/WS_INSERT_XML/NCT_INSERT_XML_LCN.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_NCT_INSERT_XML_LCN_NCT_INSERT_XML_LCN() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_NCT_INSERT_XML_LCN_NCT_INSERT_XML_LCN"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.66/WS_AUTHEN4/Authentication.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_Authentication_66_Authentication() As String
            Get
                Return CType(Me("FDA_FINANCE_Authentication_66_Authentication"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.104/WS_AUTHEN4/Authentication.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_Authentication_104_Authentication() As String
            Get
                Return CType(Me("FDA_FINANCE_Authentication_104_Authentication"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.65/ws_authen2/AUTHENTICATION.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_AUTHENTICATION_Authentication() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_AUTHENTICATION_Authentication"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.65/WS_AUTHEN4/Authentication.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_Authentication_118_Authentication() As String
            Get
                Return CType(Me("FDA_FINANCE_Authentication_118_Authentication"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://164.115.28.161/ws_update_stat_herb/WS_UPDATE.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_UPDATE_PAY_HERB_WS_UPDATE_STATUS_PAY() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_UPDATE_PAY_HERB_WS_UPDATE_STATUS_PAY"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.107/WS_LOGS_DATA/WS_INSERT_LOGS.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_INSERT_LOGS_SAI_WS_INSERT_LOGS() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_INSERT_LOGS_SAI_WS_INSERT_LOGS"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://10.111.28.161/WS_INSERT_QUEUE_LIST/WS_WAIT_QUEQE_LIST.asmx")>  _
        Public ReadOnly Property FDA_FINANCE_WS_WAIT_QUEQE_LISTS_WS_WAIT_QUEQE_LIST() As String
            Get
                Return CType(Me("FDA_FINANCE_WS_WAIT_QUEQE_LISTS_WS_WAIT_QUEQE_LIST"),String)
            End Get
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.FDA_FINANCE.My.MySettings
            Get
                Return Global.FDA_FINANCE.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
