'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_Disburse_Budget_withdraw_deka_add

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''bg_year control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bg_year As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dd_typeDeka control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dd_typeDeka As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''deka_bill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents deka_bill As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''fk_bill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fk_bill As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''txt_wd_date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_wd_date As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_DESCRIPTION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_DESCRIPTION As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''bg_group control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bg_group As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''bg_plan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bg_plan As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''bg_project control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bg_project As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dd_payS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dd_payS As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dd_payW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dd_payW As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dd_bank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dd_bank As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txt_nameAccBank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_nameAccBank As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''num_bank control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents num_bank As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rnt_amount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rnt_amount As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''rnt_vat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rnt_vat As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''rnt_vat2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rnt_vat2 As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''rnt_mulct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rnt_mulct As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''rnt_AmountIncome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rnt_AmountIncome As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''bt_save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bt_save As Global.System.Web.UI.WebControls.Button
End Class
