'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Frm_Salary_List_Employee_Insert

    '''<summary>
    '''UC_Salary_Paylist_Employee_Detail1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_Salary_Paylist_Employee_Detail1 As Global.FDA_FINANCE.UC_Salary_Paylist_Employee_Detail

    '''<summary>
    '''btn_bill_save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_bill_save As Global.System.Web.UI.WebControls.Button
End Class
