'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_Budget_Expand_Money_Detail

    '''<summary>
    '''rnt_EXPAND_AMOUNT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rnt_EXPAND_AMOUNT As Global.Telerik.Web.UI.RadNumericTextBox

    '''<summary>
    '''rdp_OVERLAP_EXPAND_DATE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdp_OVERLAP_EXPAND_DATE As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''rd_IS_OVERLAP_EXPAND control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rd_IS_OVERLAP_EXPAND As Global.System.Web.UI.WebControls.RadioButtonList
End Class
